version: '3'
services:
  nginx:
    restart: always
    image: nginx:stable
    container_name: nginx
    ports:
      - '443:443'
    volumes:
      - '/etc/nginx/conf.d:/etc/nginx/conf.d'
      - '/etc/nginx/vhost.d:/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/etc/nginx/certs:/etc/nginx/certs:ro'
    networks:
      - backend
  nginx-gen:
    restart: always
    image: jwilder/docker-gen:0.10
    container_name: nginx-gen
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/opt/docker/nginx/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro'
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - backend

networks:
  backend:
    driver: bridge
